rules:
  at-rule-blacklist: import
  at-rule-empty-line-before: never
  at-rule-name-case: lower
  at-rule-name-space-after: always
  at-rule-no-unknown:
    - true
    - ignoreAtRules: -moz-document
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-closing-brace-space-before: always
  block-no-empty: true
  block-opening-brace-newline-after: always
  block-opening-brace-newline-before:
    - never-single-line
    - never-multi-line
  block-opening-brace-space-after: always
  block-opening-brace-space-before: always
  color-hex-case: upper
  color-hex-length: short
  color-no-invalid-hex: true
  comment-empty-line-before: never
  comment-no-empty: true
  comment-whitespace-inside: always
  custom-property-empty-line-before: never
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  font-family-name-quotes: always-unless-keyword
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  font-weight-notation:
    - numeric
    - ignore: relative
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: never-multi-line
  function-parentheses-space-inside: never
  function-url-no-scheme-relative: true
  function-url-quotes: always
  function-whitespace-after: always
  indentation: 4
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-empty-lines: 0
  max-line-length: 100
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
  number-leading-zero: always
  number-max-precision: 2
  number-no-trailing-zeros: true
  property-blacklist: -moz-binding
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  rule-empty-line-before: never
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-max-empty-lines: 0
  selector-max-compound-selectors: 5
  selector-no-vendor-prefix: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown:
    - true
    - ignoreTypes: g-emoji
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: double
  time-min-milliseconds: 100
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case:
    - lower
    - ignoreKeywords: /^U\+[A-Z0-9-?]+$/
  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
